AI Recording Session # 20 Time start from 29.17 2nd part of Numpy coding
Pandas:
Pands one of the ,imp library on python for data handling and analsis.

It is used DAtascience,Data analytics,ML,BIg data....

simply it turns our raw data to strucutred and clean and analyzable form

It also built on top of numpy only.

here we have data structures called Series,Dataframe

-->Easy to use--simple like row and column kind strucutre 
-->It will integrate with other lib---numpy,matplotlib,scikit learn 
-->DAta cleaning--hadnling missing values,duplicates... 
-->Data analysis--filtering,grping,merging,aggeregating 
-->file handling--csv,excel,sql,json,html

Install:
pip install pandas

#Series--A single column(1D arraay) with index-->IT uses numpy internally

In [9]:
import pandas as pd

In [ ]:
s=pd.Series([10,20,30])# By defult Index will start from 0
s

0    10
1    20
2    30
dtype: int64

In [23]:
s=pd.Series([10,20,30],index=['a','b','c'])
s

a    10
b    20
c    30
dtype: int64

In [10]:
#Here the data is dict now we want convert this dict to DataFrame

data={"Tech":["AI","bigdata","cloud","devops","ETL tools"],"Age":[22,26,27,34,42],"Location":["USA","India","Japan","china","Aus"]}
#data={"Tech":["AI","bigdata","cloud","devops","ETL tools"],"Age":[22,26,27,34,42],"Location":["USA","India","Japan","china","Aus"]}

In [7]:
data

{'Tech': ['AI', 'bigdata', 'cloud', 'devops', 'ETL tools'],
 'Age': [22, 26, 27, 34, 42],
 'Location': ['USA', 'India', 'Japan', 'china', 'Aus']}

Data frames:Like a table-->rows and columns
Pandas built on numpy arrays so here dataframe is collection series objects Again that is internally a numpy array. Default index starts with 0 IF we want to change yes we can change by using index parameter

In [11]:
df=pd.DataFrame(data,index=['a','b','c','d','e'])
df

        Tech  Age Location
a         AI   22      USA
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [10]:
df1=pd.DataFrame(data)
df1

        Tech  Age Location
0         AI   22      USA
1    bigdata   26    India
2      cloud   27    Japan
3     devops   34    china
4  ETL tools   42      Aus

In [15]:
df

        Tech  Age Location
a         AI   22      USA
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [ ]:
data#This will print no structure so we can creatr a Data Frame = df

{'Tech': ['AI', 'bigdata', 'cloud', 'devops', 'ETL tools'],
 'Age': [22, 26, 27, 34, 42],
 'Location': ['USA', 'India', 'Japan', 'china', 'Aus']}

Data frames:Like a table-->rows and columns
Pandas built on numpy arrays so here dataframe is collection series objects Again that is internally a numpy array. Default index starts with 0 IF we want to change yes we can change by using index parameter

In [26]:
df=pd.DataFrame(data,index=['a','b','c','d','e'])
df

        Tech  Age Location
a         AI   22      USA
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [ ]:
df1=pd.DataFrame(data)# Here did not put any Index sot it will give defult 0,1,2...
df1

        Tech  Age Location
0         AI   22      USA
1    bigdata   26    India
2      cloud   27    Japan
3     devops   34    china
4  ETL tools   42      Aus

In [28]:
df

        Tech  Age Location
a         AI   22      USA
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

#AI Recording session #21 start from here

Checking properties of dataframe

In [16]:
df.shape

(5, 3)

In [ ]:
df.info()# String will take as Object and Digit as Integer

<class 'pandas.DataFrame'>
Index: 5 entries, a to e
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Tech      5 non-null      str
 1   Age       5 non-null      int64
 2   Location  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 332.0+ bytes

In [18]:
df.columns

Index(['Tech', 'Age', 'Location'], dtype='str')

In [19]:
df.describe()#IT applies all stats techniques on integer column here

             Age
count   5.000000
mean   30.200000
std     7.886698
min    22.000000
25%    26.000000
50%    27.000000
75%    34.000000
max    42.000000

## Indexing
loc[] and iloc[]:
loc[]-->Location-->is label based to get the elements iloc[]-->Integer location--> It selects index positions with inetger.
iloc[]--> Integer location--> It selects index positions with integer.

In [20]:
df

        Tech  Age Location
a         AI   22      USA
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [21]:
df.loc['a']

Tech         AI
Age          22
Location    USA
Name: a, dtype: object

In [29]:
df.iloc[0]

Tech         AI
Age          22
Location    USA
Name: a, dtype: object

In [14]:
df.iloc['a']# We will get eoore This index should be digit in integer

TypeError: Cannot index by location index with a non-integer key

In [31]:
df1.loc[0] # This will print 1st raw

Tech         AI
Age          22
Location    USA
Name: 0, dtype: object

In [32]:
df1.iloc[0] # This will get same results

Tech         AI
Age          22
Location    USA
Name: 0, dtype: object

In [33]:
df.loc['c']

Tech        cloud
Age            27
Location    Japan
Name: c, dtype: object

In [34]:
df.iloc[2]

Tech        cloud
Age            27
Location    Japan
Name: c, dtype: object

In [ ]:
df.iloc[1:4] # We can use some split also

      Tech  Age Location
b  bigdata   26    India
c    cloud   27    Japan
d   devops   34    china

In [36]:
df.loc['a':'c']

      Tech  Age Location
a       AI   22      USA
b  bigdata   26    India
c    cloud   27    Japan

In [37]:
df.iloc[:1]

  Tech  Age Location
a   AI   22      USA

In [38]:
df.iloc[:,1]

a    22
b    26
c    27
d    34
e    42
Name: Age, dtype: int64

In [ ]:
df.iloc[:] # This will print everything

        Tech  Age Location
a         AI   22      USA
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [ ]:
df.iloc[:1] #Here no coma so will print only 1st raw

  Tech  Age Location
a   AI   22      USA

In [ ]:
df.iloc[:,1]# Here with coma and 1 will print Indix and 2nd columan, All the raws and 2nd columan

a    22
b    26
c    27
d    34
e    42
Name: Age, dtype: int64

In [44]:
df.iloc[:,2] #This will print only all locations

a      USA
b    India
c    Japan
d    china
e      Aus
Name: Location, dtype: str

In [ ]:
df.iloc[:2] #This will print 1st two raws

      Tech  Age Location
a       AI   22      USA
b  bigdata   26    India

In [47]:
df1

        Tech  Age Location
0         AI   22      USA
1    bigdata   26    India
2      cloud   27    Japan
3     devops   34    china
4  ETL tools   42      Aus

In [48]:
df1.loc[:"Age"]

        Tech  Age Location
0         AI   22      USA
1    bigdata   26    India
2      cloud   27    Japan
3     devops   34    china
4  ETL tools   42      Aus

In [49]:
df1.loc[:,"Age"]

0    22
1    26
2    27
3    34
4    42
Name: Age, dtype: int64

In [56]:
df.loc[['a','b']]#This will print two raws

      Tech  Age Location
a       AI   22      USA
b  bigdata   26    India

In [17]:
df.loc['c'][2]

KeyError: 2

In [101]:
df.loc['c']['Location']

'Japan'

In [18]:
df

        Tech  Age Location
a         AI   22      USA
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [19]:
df.loc['c'][2]

KeyError: 2

In [79]:
df

        Tech  Age Location
a         AI   22      USA
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [20]:
df.loc['c']['Location']

'Japan'

In [21]:
df

        Tech  Age Location
a         AI   22      USA
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [22]:
df.loc['c'][[1,2]]

KeyError: "None of [Index([1, 2], dtype='int64')] are in the [index]"

In [63]:
df.loc['c'][['Age','Location']]

Age            27
Location    Japan
Name: c, dtype: object

In [64]:
df.loc["a":"c"]#inclusive the start and ending labels--a,b,c are included

      Tech  Age Location
a       AI   22      USA
b  bigdata   26    India
c    cloud   27    Japan

In [ ]:
df.loc['c'][2]#This will print only Japan

KeyError: 2

In [73]:
df.loc['c'][[1,2]]

KeyError: "None of [Index([1, 2], dtype='int64')] are in the [index]"

In [89]:
df.loc['c']['Location']

'Japan'

In [24]:
df.loc["a":"c"]

      Tech  Age Location
a       AI   22      USA
b  bigdata   26    India
c    cloud   27    Japan

In [70]:
df

        Tech  Age Location
a         AI   22      USA
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [ ]:
df.loc[df['Age']>24]# Check some condition

        Tech  Age Location
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

C:\Users\jaiam\OneDrive\2026\Training_2026\H2kInfosys-2026\AI_Data

df=pd.read_csv("C:\\Users\\kumar\\Desktop\\amazon.csv")
df=pd.read_csv("C:/Users/jaiam/OneDrive/2026/Training_2026\H2kInfosys-2026/AI_Dataamazon.csv")

In [71]:
df['Age']>24

a    False
b     True
c     True
d     True
e     True
Name: Age, dtype: bool

In [26]:
df.loc[df['Age']>24]

        Tech  Age Location
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [30]:
df.loc[df.Age>24]

        Tech  Age Location
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [32]:
df.loc[df.Age>24,"Age"]

b    26
c    27
d    34
e    42
Name: Age, dtype: int64

In [36]:
df[df['Age']>24].iloc[:,1]

b    26
c    27
d    34
e    42
Name: Age, dtype: int64

#iloc--position based  Start video #20 from 37.51

In [38]:
df[df["Age"]>24].iloc[1]

Tech        cloud
Age            27
Location    Japan
Name: c, dtype: object

In [40]:
df[df["Age"]>24]

        Tech  Age Location
b    bigdata   26    India
c      cloud   27    Japan
d     devops   34    china
e  ETL tools   42      Aus

In [ ]:
df[df["Age"]>24].iloc[:,1]# Here we use iLog outside of condition while loc inside loc condition

b    26
c    27
d    34
e    42
Name: Age, dtype: int64

In [ ]:
df.iloc[1]# This will print only 1st raw

Tech        bigdata
Age              26
Location      India
Name: b, dtype: object

In [43]:
df.iloc[[0,2],[1,2]]
#here taking [0,2]--> as rows
#[1,2] as columns

   Age Location
a   22      USA
c   27    Japan

In [44]:
df.iloc[[0,2],[0,2]]
#here taking [0,2]--> as rows
#[1,2] as columns

    Tech Location
a     AI      USA
c  cloud    Japan

In [45]:
df.iloc[[0,2],[0,1,2]]
#here taking [0,2]--> as rows
#[1,2] as columns

    Tech  Age Location
a     AI   22      USA
c  cloud   27    Japan

In [47]:
df.iloc[[0,2],[2]]
#here taking [0,2]--> as rows
#[1,2] as columns

  Location
a      USA
c    Japan

End od AI Session #21