AI Session 33 HW. visulizations on EDA Flight Test Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

!pip install openpyxl

python.exe -m pip install --upgrade pip

In [3]:
dfv=pd.read_excel("C:/Users/jaiam/OneDrive/2026/Training_2026/H2kInfosys-2026/AI_Data/flight_price.xlsx")

In [4]:
dfv.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [5]:
dfv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [6]:
dfv.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='str')

In [7]:
dfv.describe()#a basic statistics on numeric column

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [8]:
dfv.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [9]:
dfv.dropna(inplace=True)

In [10]:
dfv.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

Feature engineering:
Process of creating,transforming ,selecting input features.
dt is some variable

In [11]:
dfv["Journey_Day"]=pd.to_datetime(dfv["Date_of_Journey"],format=("%d/%m/%Y")).dt.day

In [12]:
dfv["Journey_Month"]=pd.to_datetime(dfv["Date_of_Journey"],format=("%d/%m/%Y")).dt.month

In [13]:
dfv.info()

<class 'pandas.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  str
 1   Date_of_Journey  10682 non-null  str
 2   Source           10682 non-null  str
 3   Destination      10682 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10682 non-null  str
 6   Arrival_Time     10682 non-null  str
 7   Duration         10682 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10682 non-null  str
 10  Price            10682 non-null  int64
 11  Journey_Day      10682 non-null  int32
 12  Journey_Month    10682 non-null  int32
dtypes: int32(2), int64(1), str(10)
memory usage: 1.1 MB

In [14]:
dfv['Journey_Day']

0        24
1         1
2         9
3        12
4         1
         ..
10678     9
10679    27
10680    27
10681     1
10682     9
Name: Journey_Day, Length: 10682, dtype: int32

In [15]:
dfv['Journey_Month']

0        3
1        5
2        6
3        5
4        3
        ..
10678    4
10679    4
10680    4
10681    3
10682    5
Name: Journey_Month, Length: 10682, dtype: int32

axis->0 ->vertical direction-->rows 
axis->1 ->horizontal direction-->columns

In [16]:
dfv.drop(["Date_of_Journey"],axis=1,inplace=True)

In [17]:
dfv.info()

<class 'pandas.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  str
 1   Source           10682 non-null  str
 2   Destination      10682 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10682 non-null  str
 5   Arrival_Time     10682 non-null  str
 6   Duration         10682 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10682 non-null  str
 9   Price            10682 non-null  int64
 10  Journey_Day      10682 non-null  int32
 11  Journey_Month    10682 non-null  int32
dtypes: int32(2), int64(1), str(9)
memory usage: 1001.4 KB

In [18]:
dfv["Dept_Hour"]=pd.to_datetime(dfv["Dep_Time"]).dt.hour

C:\Users\jaiam\AppData\Local\Temp\ipykernel_32932\4044266110.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dfv["Dept_Hour"]=pd.to_datetime(dfv["Dep_Time"]).dt.hour

In [19]:
dfv["Dept_Min"]=pd.to_datetime(dfv["Dep_Time"]).dt.minute

C:\Users\jaiam\AppData\Local\Temp\ipykernel_32932\1195015635.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dfv["Dept_Min"]=pd.to_datetime(dfv["Dep_Time"]).dt.minute

In [20]:
dfv.info()

<class 'pandas.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  str
 1   Source           10682 non-null  str
 2   Destination      10682 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10682 non-null  str
 5   Arrival_Time     10682 non-null  str
 6   Duration         10682 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10682 non-null  str
 9   Price            10682 non-null  int64
 10  Journey_Day      10682 non-null  int32
 11  Journey_Month    10682 non-null  int32
 12  Dept_Hour        10682 non-null  int32
 13  Dept_Min         10682 non-null  int32
dtypes: int32(4), int64(1), str(9)
memory usage: 1.1 MB

In [21]:
dfv["Dept_Hour"]

0        22
1         5
2         9
3        18
4        16
         ..
10678    19
10679    20
10680     8
10681    11
10682    10
Name: Dept_Hour, Length: 10682, dtype: int32

In [22]:
dfv["Dept_Min"]

0        20
1        50
2        25
3         5
4        50
         ..
10678    55
10679    45
10680    20
10681    30
10682    55
Name: Dept_Min, Length: 10682, dtype: int32

In [23]:
dfv["Duration_Hours"]=dfv["Duration"].str.extract('(\d+)h').fillna(0).astype(int)
dfv["Duration_minsrs"]=dfv["Duration"].str.extract('(\d+)m').fillna(0).astype(int)
dfv["Dept_Hour"]

0        22
1         5
2         9
3        18
4        16
         ..
10678    19
10679    20
10680     8
10681    11
10682    10
Name: Dept_Hour, Length: 10682, dtype: int32

In [24]:
dfv["Dept_Min"]

0        20
1        50
2        25
3         5
4        50
         ..
10678    55
10679    45
10680    20
10681    30
10682    55
Name: Dept_Min, Length: 10682, dtype: int32

In [25]:
dfv.info()

<class 'pandas.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  str
 1   Source           10682 non-null  str
 2   Destination      10682 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10682 non-null  str
 5   Arrival_Time     10682 non-null  str
 6   Duration         10682 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10682 non-null  str
 9   Price            10682 non-null  int64
 10  Journey_Day      10682 non-null  int32
 11  Journey_Month    10682 non-null  int32
 12  Dept_Hour        10682 non-null  int32
 13  Dept_Min         10682 non-null  int32
 14  Duration_Hours   10682 non-null  int64
 15  Duration_minsrs  10682 non-null  int64
dtypes: int32(4), int64(3), str(9)
memory usage: 1.2 MB

In [26]:
dfv['Total_Stops'].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', '4 stops']
Length: 5, dtype: str

In [29]:
dfv["Total_Stops"]=dfv["Total_Stops"].map({"non-stop":0,"1 stop":1,"2 stops":2,"3 stops":3,"4 stops":4})

In [30]:
dfv["Total_Stops"]

0        0
1        2
2        2
3        1
4        1
        ..
10678    0
10679    0
10680    0
10681    0
10682    2
Name: Total_Stops, Length: 10682, dtype: int64